// ====== 雷霆战机 - 全装备数据文件 ======
// 此文件由后台管理系统自动生成，也可手动编辑

window.PAGE_CONFIG = {
  title: "雷霆战机 - 全装备数据图鉴 | 天游工作室",
  header: {
    title: "雷霆战机",
    subtitle: "天 游 工 作 室 · 全 装 备 数 据 图 鉴"
  },
  statsLabels: ["当 前 显 示", "战 机", "装 甲", "副 武 器", "僚 机", "战 神"],
  mainTabs: {
    star5: "✦ 五星装备",
    god: "✦ 战神装备"
  },
  subTabs: {
    all: "全部",
    fighter: "✈ 战机",
    armor: "🛡 装甲",
    subweapon: "◎ 副武器",
    wingman: "✦ 僚机"
  },
  godSubTabs: {
    "god-all": "全部",
    "god-fighter": "✈ 战神机体",
    "god-armor": "🛡 战神装甲",
    "god-sub": "◎ 战神副武器",
    "god-wing": "✦ 战神僚机"
  },
  searchPlaceholder: "搜索装备名称 · 系列 · 特技 · 合成材料 …",
  sectionTitles: {
    fighter: "✈ 战机",
    armor: "🛡 装甲",
    subweapon: "◎ 副武器",
    wingman: "✦ 僚机"
  },
  godSectionTitles: {
    fighter: "✈ 战神机体",
    armor: "🛡 战神装甲",
    sub: "◎ 战神副武器",
    wing: "✦ 战神僚机"
  },
  footer: {
    line1: "数据来源：雷霆战机 Fandom Wiki · 官方资料站 · 玩家社区攻略",
    line2: "装备数据以游戏内实际版本为准  |  天游工作室  |  Tencent"
  }
};

window.STAR5_DATA = {
  fighter: [
    {name:'雷霆突击',series:'突击',evo:'突击零式 → 脉冲突击 → 迅雷突击 → 雷霆突击',atk:'2900',tier:5,skill:'普通',skillNote:'基础型，无特殊效果',rank:'五等',img:''},
    {name:'雷霆尖峰',series:'尖峰',evo:'尖峰零式 → 脉冲尖峰 → 迅雷尖峰 → 雷霆尖峰',atk:'3010',tier:4,skill:'贯穿',skillNote:'弹幕穿透敌人',rank:'四等',img:''},
    {name:'怒火凤凰',series:'猛禽',evo:'猛禽零式 → 烈风战鹰 → 暴风狮鹫 → 怒火凤凰',atk:'3150',tier:3,skill:'范围',skillNote:'火焰弹幕范围清场',rank:'三等',img:''},
    {name:'极光幻影',series:'幻影',evo:'幻影零式 → 疾风幻影 → 虚空幻影 → 极光幻影',atk:'3303',tier:2,skill:'激光',skillNote:'全屏穿透激光弹幕',rank:'二等',img:''},
    {name:'神魔异形',series:'异形',evo:'异形零式 → 钢铁异形 → 爆裂异形 → 神魔异形',atk:'3415',tier:1,skill:'贯穿',skillNote:'顶级贯穿伤害，早期版本最强',rank:'一等',img:''},
    {name:'智慧曙光',series:'曙光',evo:'曙光零式 → 和平曙光 → 希望曙光 → 智慧曙光',atk:'3415',tier:1,skill:'散射',skillNote:'多方向散射弹幕，清屏利器',rank:'一等',img:''},
    {name:'魔王刀锋',series:'刀锋',evo:'刀锋零式 → 异界刀锋 → 恶魔刀锋 → 魔王刀锋',atk:'3527',tier:1,skill:'穿刺+斩击',skillNote:'穿刺斩击双重伤害，顶级输出',rank:'一等',img:''},
    {name:'X翼冰河',series:'冰河',evo:'冰河零式 → 风暴冰河 → 星云冰河 → X翼冰河',atk:'3527',tier:1,skill:'急冻',skillNote:'冰冻减速+高额单体伤害',rank:'一等',img:''},
    {name:'异星魅影',series:'魅影',evo:'魅影零式 → 黑暗魅影 → 深渊魅影 → 异星魅影',atk:'3303',tier:2,skill:'魅影',skillNote:'暗影系进阶弹幕',rank:'二等',img:''},
    {name:'镜面虚幻',series:'虚幻',evo:'虚幻零式 → 迷彩虚幻 → 拟态虚幻 → 镜面虚幻',atk:'3303',tier:2,skill:'反射',skillNote:'镜面反射敌方子弹',rank:'二等',img:''},
    {name:'跃动辉光',series:'辉光',evo:'辉光零式 → 辐射辉光 → 迷幻辉光 → 跃动辉光',atk:'3150',tier:3,skill:'辉光',skillNote:'跳跃辉光散射攻击',rank:'三等',img:''},
    {name:'金箍神铁',series:'神铁',evo:'神铁零式 → 铜筋神铁 → 银辉神铁 → 金箍神铁',atk:'3415',tier:1,skill:'重击',skillNote:'重型金属弹幕攻击',rank:'一等',img:''},
    {name:'紫霞铃音',series:'铃音',evo:'铃音零式 → 碧羽铃音 → 蓝翎铃音 → 紫霞铃音',atk:'3150',tier:3,skill:'音波',skillNote:'音波震荡攻击',rank:'三等',img:''},
    {name:'绯霞流火',series:'流火',evo:'流火零式 → 赤穹流火 → 彤云流火 → 绯霞流火',atk:'3150',tier:3,skill:'流火',skillNote:'持续性火焰灼烧伤害',rank:'三等',img:''},
    {name:'彩翼分辉',series:'分辉',evo:'分辉零式 → 聚焦分辉 → 四色分辉 → 彩翼分辉',atk:'3303',tier:2,skill:'分光',skillNote:'多重彩色弹幕',rank:'二等',img:''},
    {name:'合金幻刃',series:'合金',evo:'合金零式 → 合金翠锋 → 合金苍翼 → 合金幻刃',atk:'3303',tier:2,skill:'合金',skillNote:'合金强化利刃弹幕',rank:'二等',img:''},
    {name:'星火蜉蝣',series:'蜉蝣',evo:'蜉蝣零式 → 隐翅蜉蝣 → 蜻翼蜉蝣 → 星火蜉蝣',atk:'3415',tier:1,skill:'蜉蝣',skillNote:'浮游炮式自主攻击',rank:'一等',img:''},
    {name:'星辉夜蝠',series:'夜蝠',evo:'夜蝠零式 → 玲珑夜蝠 → 锐爪夜蝠 → 星辉夜蝠',atk:'3415',tier:1,skill:'暗袭',skillNote:'暗夜环境攻击加成',rank:'一等',img:''},
    {name:'雅典战火',series:'雅典',evo:'雅典之火 → 雅典原火 → 雅典初火 → 雅典战火',atk:'3415',tier:1,skill:'神火',skillNote:'神圣火焰灼烧',rank:'一等',img:''},
    {name:'暴龙战颚',series:'暴龙',evo:'暴龙原颚 → 暴龙初颚 → 暴龙战颚',atk:'3415',tier:1,skill:'撕裂',skillNote:'暴龙撕咬攻击',rank:'一等',img:''},
    {name:'银须战锤',series:'银须',evo:'银须之锤 → 银须巨锤 → 银须战锤',atk:'3415',tier:1,skill:'重锤',skillNote:'锤击范围震荡伤害',rank:'一等',img:''},
    {name:'帝君圣刃',series:'帝君',evo:'帝君之刃 → 帝君战刃 → 帝君圣刃',atk:'3527',tier:1,skill:'圣斩',skillNote:'神圣斩击，顶级伤害',rank:'一等',img:''},
    {name:'狮心幻骑',series:'狮心',evo:'狮心之骑 → 狮心战骑 → 狮心幻骑',atk:'3415',tier:1,skill:'冲锋',skillNote:'骑士冲锋贯穿攻击',rank:'一等',img:''},
    {name:'凯旋重剑',series:'凯旋',evo:'凯旋之剑 → 凯旋战剑 → 凯旋重剑',atk:'3415',tier:1,skill:'重斩',skillNote:'重型剑刃斩击',rank:'一等',img:''},
    {name:'兽王狂弹',series:'兽王',evo:'兽王铁弹 → 兽王炎弹 → 兽王狂弹',atk:'3415',tier:1,skill:'狂野',skillNote:'野兽系狂暴弹幕',rank:'一等',img:''},
    {name:'百媚幻狐',series:'百媚',evo:'百媚丽狐 → 百媚迷狐 → 百媚幻狐',atk:'3303',tier:2,skill:'魅惑',skillNote:'魅惑系特殊弹幕效果',rank:'二等',img:''},
    {name:'烈阳神辉',series:'烈阳',evo:'烈阳光辉 → 烈阳灵辉 → 烈阳神辉',atk:'3415',tier:1,skill:'烈阳',skillNote:'烈阳灼烧持续伤害',rank:'一等',img:''},
    {name:'震海狂波',series:'震海',evo:'震海之波 → 震海碧波 → 震海狂波',atk:'3415',tier:1,skill:'波涛',skillNote:'波浪式扩散攻击',rank:'一等',img:''},
    {name:'永夜新星',series:'永夜',evo:'永夜之星 → 永夜澜星 → 永夜新星',atk:'3415',tier:1,skill:'永夜',skillNote:'暗夜星辰爆发伤害',rank:'一等',img:''},
    {name:'荆棘利刺',series:'荆棘',evo:'荆棘之刺 → 荆棘突刺 → 荆棘利刺',atk:'3303',tier:2,skill:'穿刺',skillNote:'荆棘穿透攻击',rank:'二等',img:''},
    {name:'苍穹灵矛',series:'苍穹',evo:'苍穹之矛 → 苍穹尖矛 → 苍穹灵矛',atk:'3415',tier:1,skill:'投射',skillNote:'远程灵矛投射',rank:'一等',img:''},
    {name:'神火烈焰',series:'神火',evo:'神火之焰 → 神火初焰 → 神火烈焰',atk:'3527',tier:1,skill:'神焰',skillNote:'最强火焰系伤害',rank:'一等',img:''}
  ],
  armor: [
    {name:'金刚之盾',series:'金刚',evo:'金刚零式 → 金刚坚壳 → 金刚护甲 → 金刚之盾',hp:'48000',defScore:'2400',tier:5,skill:'钢盾',skillNote:'概率减免伤害',rank:'五等',img:''},
    {name:'神圣之力',series:'祝福',evo:'祝福零式 → 祝福之光 → 祝福之力 → 神圣之力',hp:'52000',defScore:'2600',tier:4,skill:'神圣',skillNote:'满血时防止被秒杀',rank:'四等',img:''},
    {name:'黄金之铠',series:'黄金',evo:'黄金零式 → 黄金护甲 → 黄金战甲 → 黄金之铠',hp:'61600',defScore:'3080',tier:3,skill:'战魂',skillNote:'被击中10%概率触发暴走',rank:'三等',img:''},
    {name:'聚能之光',series:'聚能',evo:'聚能零式 → 聚能护盾 → 聚能装甲 → 聚能之光',hp:'63840',defScore:'3192',tier:2,skill:'荣耀',skillNote:'擦弹获得额外分数',rank:'二等',img:''},
    {name:'魔龙之鳞',series:'魔龙',evo:'魔龙零式 → 魔龙鳞甲 → 魔龙护甲 → 魔龙之鳞',hp:'66080',defScore:'3304',tier:1,skill:'龙血',skillNote:'自动回复生命值，新手神器',rank:'一等',img:''},
    {name:'月光之轮',series:'月光',evo:'月光零式 → 月光护盾 → 月光装甲 → 月光之轮',hp:'68320',defScore:'3416',tier:1,skill:'守护',skillNote:'周期性生成防护盾',rank:'一等',img:''},
    {name:'原生之华',series:'原生',evo:'原生零式 → 原生护甲 → 原生之盾 → 原生之华',hp:'70560',defScore:'3528',tier:1,skill:'转化',skillNote:'拾取水晶回复生命',rank:'一等',img:''},
    {name:'红莲之怒',series:'红莲',evo:'红莲零式 → 红莲护甲 → 红莲战甲 → 红莲之怒',hp:'68320',defScore:'3416',tier:1,skill:'反伤',skillNote:'受到攻击时火焰反伤',rank:'一等',img:''},
    {name:'溯时之源',series:'溯时',evo:'溯时零式 → 溯时之盾 → 溯时护甲 → 溯时之源',hp:'66080',defScore:'3304',tier:1,skill:'回溯',skillNote:'时间回溯减免伤害',rank:'一等',img:''},
    {name:'狂热之意',series:'狂热',evo:'狂热零式 → 狂热护甲 → 狂热战甲 → 狂热之意',hp:'63840',defScore:'3192',tier:2,skill:'狂热',skillNote:'生命越低攻击越高',rank:'二等',img:''},
    {name:'凝结之刻',series:'凝结',evo:'凝结零式 → 凝结之盾 → 凝结护甲 → 凝结之刻',hp:'66080',defScore:'3304',tier:1,skill:'冰结',skillNote:'冻结效果减免伤害',rank:'一等',img:''},
    {name:'血怒之心',series:'血怒',evo:'血怒零式 → 血怒护甲 → 血怒战甲 → 血怒之心',hp:'68320',defScore:'3416',tier:1,skill:'血怒',skillNote:'击杀敌人回复生命',rank:'一等',img:''},
    {name:'渊舞之岗',series:'渊舞',evo:'渊舞零式 → 渊舞之盾 → 渊舞护甲 → 渊舞之岗',hp:'66080',defScore:'3304',tier:1,skill:'深渊',skillNote:'深渊环境防御加成',rank:'一等',img:''},
    {name:'清辉之灵',series:'清辉',evo:'清辉零式 → 清辉护甲 → 清辉之盾 → 清辉之灵',hp:'63840',defScore:'3192',tier:2,skill:'净化',skillNote:'周期性清除负面效果',rank:'二等',img:''},
    {name:'名远之威',series:'名远',evo:'名远零式 → 名远护甲 → 名远战甲 → 名远之威',hp:'61600',defScore:'3080',tier:3,skill:'威压',skillNote:'威慑降低敌人伤害',rank:'三等',img:''},
    {name:'反冲之障',series:'反冲',evo:'反冲零式 → 反冲护盾 → 反冲破障 → 反冲之障',hp:'66080',defScore:'3304',tier:1,skill:'反冲',skillNote:'受击反弹伤害',rank:'一等',img:''},
    {name:'寂静之围',series:'寂静',evo:'寂静零式 → 寂静护甲 → 寂静围场 → 寂静之围',hp:'70560',defScore:'3528',tier:1,skill:'寂静',skillNote:'展开沉默减伤领域',rank:'一等',img:''},
    {name:'灭却之域',series:'灭却',evo:'灭却零式 → 灭却护甲 → 灭却领域 → 灭却之域',hp:'70560',defScore:'3528',tier:1,skill:'灭却',skillNote:'超大范围伤害减免',rank:'一等',img:''},
    {name:'雅典战盔',series:'雅典',evo:'— → 雅典原盔 → 雅典初盔 → 雅典战盔',hp:'70560',defScore:'3528',tier:1,skill:'神佑',skillNote:'雅典系列神圣防御',rank:'一等',img:''},
    {name:'暴龙战甲',series:'暴龙',evo:'— → 暴龙原甲 → 暴龙初甲 → 暴龙战甲',hp:'70560',defScore:'3528',tier:1,skill:'龙甲',skillNote:'暴龙系列龙鳞防御',rank:'一等',img:''},
    {name:'银须战盾',series:'银须',evo:'— → 银须之盾 → 银须巨盾 → 银须战盾',hp:'68320',defScore:'3416',tier:1,skill:'巨盾',skillNote:'巨盾格挡减伤',rank:'一等',img:''},
    {name:'帝君圣铠',series:'帝君',evo:'— → 帝君之铠 → 帝君战铠 → 帝君圣铠',hp:'70560',defScore:'3528',tier:1,skill:'圣佑',skillNote:'帝君系列神圣护甲',rank:'一等',img:''},
    {name:'狮心幻盔',series:'狮心',evo:'— → 狮心之盔 → 狮心战盔 → 狮心幻盔',hp:'66080',defScore:'3304',tier:1,skill:'狮心',skillNote:'狮心系列防护加成',rank:'一等',img:''},
    {name:'凯旋重甲',series:'凯旋',evo:'— → 凯旋之甲 → 凯旋战甲 → 凯旋重甲',hp:'70560',defScore:'3528',tier:1,skill:'重甲',skillNote:'重型装甲超高防御',rank:'一等',img:''},
    {name:'兽王狂铠',series:'兽王',evo:'— → 兽王之铠 → 兽王战铠 → 兽王狂铠',hp:'68320',defScore:'3416',tier:1,skill:'狂铠',skillNote:'狂暴状态防御提升',rank:'一等',img:''},
    {name:'百媚幻罗',series:'百媚',evo:'— → 百媚之罗 → 百媚战罗 → 百媚幻罗',hp:'63840',defScore:'3192',tier:2,skill:'幻罗',skillNote:'魅惑敌人降低伤害',rank:'二等',img:''},
    {name:'烈阳神盾',series:'烈阳',evo:'— → 烈阳之盾 → 烈阳灵盾 → 烈阳神盾',hp:'70560',defScore:'3528',tier:1,skill:'神盾',skillNote:'烈阳灼烧近身敌人',rank:'一等',img:''},
    {name:'震海湛晶',series:'震海',evo:'— → 震海之晶 → 震海碧晶 → 震海湛晶',hp:'68320',defScore:'3416',tier:1,skill:'湛晶',skillNote:'水晶护盾回复加成',rank:'一等',img:''},
    {name:'永夜暗铠',series:'永夜',evo:'— → 永夜之铠 → 永夜战铠 → 永夜暗铠',hp:'70560',defScore:'3528',tier:1,skill:'暗铠',skillNote:'暗夜属性强化防御',rank:'一等',img:''},
    {name:'荆棘猎甲',series:'荆棘',evo:'— → 荆棘之甲 → 荆棘战甲 → 荆棘猎甲',hp:'63840',defScore:'3192',tier:2,skill:'猎甲',skillNote:'荆棘反伤护甲',rank:'二等',img:''},
    {name:'苍穹爆炎',series:'苍穹',evo:'— → 苍穹之甲 → 苍穹战甲 → 苍穹爆炎',hp:'70560',defScore:'3528',tier:1,skill:'爆炎',skillNote:'受击爆炸反击',rank:'一等',img:''},
    {name:'神火重铠',series:'神火',evo:'— → 神火之铠 → 神火战铠 → 神火重铠',hp:'70560',defScore:'3528',tier:1,skill:'重铠',skillNote:'神火系列顶级重甲',rank:'一等',img:''}
  ],
  subweapon: [
    {name:'巡航导弹',series:'导弹',evo:'跟踪导弹 → 精确导弹 → 制导导弹 → 巡航导弹',atk:'2855',tier:5,skill:'跟踪',skillNote:'8枚自动追踪导弹',rank:'五等',img:''},
    {name:'贫铀穿甲弹',series:'穿甲',evo:'穿甲弹 → 高爆穿甲弹 → 重铀穿甲弹 → 贫铀穿甲弹',atk:'2967',tier:4,skill:'贯穿',skillNote:'4枚穿透弹，贴脸杀BOSS',rank:'四等',img:''},
    {name:'闪电新星',series:'闪电',evo:'闪电球 → 闪电链 → 闪电风暴 → 闪电新星',atk:'3079',tier:3,skill:'追踪+范围',skillNote:'6颗追踪闪电球',rank:'三等',img:''},
    {name:'融合核弹',series:'核弹',evo:'小型核弹 → 中型核弹 → 大型核弹 → 融合核弹',atk:'3191',tier:2,skill:'范围',skillNote:'2颗超大范围核弹',rank:'二等',img:''},
    {name:'聚能爆破弹',series:'爆破',evo:'爆破弹 → 高能爆破弹 → 烈性爆破弹 → 聚能爆破弹',atk:'3303',tier:1,skill:'贯穿+范围',skillNote:'贯穿敌人并产生爆炸',rank:'一等',img:''},
    {name:'超导激光',series:'激光',evo:'激光器 → 高能激光 → 离子激光 → 超导激光',atk:'3415',tier:1,skill:'锁定',skillNote:'4束自动锁定激光',rank:'一等',img:''},
    {name:'噬能孢子',series:'孢子',evo:'能量孢子 → 噬能孢子 → 噬能孢子 → 噬能孢子',atk:'3303',tier:1,skill:'吞噬',skillNote:'吸取敌人能量转化伤害',rank:'一等',img:''},
    {name:'震荡干涉波',series:'震荡',evo:'震波 → 震荡波 → 干涉波 → 震荡干涉波',atk:'3303',tier:1,skill:'震荡',skillNote:'震荡波范围伤害',rank:'一等',img:''},
    {name:'空间湮灭波',series:'湮灭',evo:'湮灭波 → 空间湮灭波 → 空间湮灭波 → 空间湮灭波',atk:'3415',tier:1,skill:'湮灭',skillNote:'空间湮灭超大范围伤害',rank:'一等',img:''},
    {name:'归零矩阵',series:'归零',evo:'归零器 → 归零阵列 → 归零矩阵 → 归零矩阵',atk:'3415',tier:1,skill:'归零',skillNote:'清除敌方弹幕',rank:'一等',img:''},
    {name:'尖晶星芒',series:'星芒',evo:'星芒 → 尖晶星芒 → 尖晶星芒 → 尖晶星芒',atk:'3191',tier:2,skill:'星芒',skillNote:'散射星芒攻击',rank:'二等',img:''},
    {name:'黑枪四圣',series:'黑枪',evo:'黑枪 → 黑枪四圣 → 黑枪四圣 → 黑枪四圣',atk:'3303',tier:1,skill:'四圣',skillNote:'四方向暗黑枪击',rank:'一等',img:''},
    {name:'紫青旋影',series:'旋影',evo:'旋影 → 紫青旋影 → 紫青旋影 → 紫青旋影',atk:'3191',tier:2,skill:'旋转',skillNote:'旋转弹幕攻击',rank:'二等',img:''},
    {name:'频闪爆弹',series:'频闪',evo:'频闪弹 → 频闪爆弹 → 频闪爆弹 → 频闪爆弹',atk:'3303',tier:1,skill:'频闪',skillNote:'高频闪光伴随爆炸',rank:'一等',img:''},
    {name:'破坏力场',series:'力场',evo:'力场 → 破坏力场 → 破坏力场 → 破坏力场',atk:'3415',tier:1,skill:'力场',skillNote:'持续伤害力场',rank:'一等',img:''},
    {name:'动能破片弹',series:'破片',evo:'破片弹 → 动能破片弹 → 动能破片弹 → 动能破片弹',atk:'3303',tier:1,skill:'破片',skillNote:'爆炸碎片范围伤害',rank:'一等',img:''},
    {name:'红移谐振波',series:'谐振',evo:'谐振波 → 红移谐振波 → 红移谐振波 → 红移谐振波',atk:'3303',tier:1,skill:'谐振',skillNote:'谐振连锁传递伤害',rank:'一等',img:''},
    {name:'幻视魔眼炮',series:'魔眼',evo:'魔眼 → 幻视魔眼 → 幻视魔眼炮 → 幻视魔眼炮',atk:'3415',tier:1,skill:'幻视',skillNote:'迷惑敌人并造成伤害',rank:'一等',img:''},
    {name:'雅典战弓',series:'雅典',evo:'— → 雅典之弓 → 雅典战弓 → 雅典战弓',atk:'3415',tier:1,skill:'神箭',skillNote:'雅典系列神圣射击',rank:'一等',img:''},
    {name:'暴龙战吼',series:'暴龙',evo:'— → 暴龙之吼 → 暴龙战吼 → 暴龙战吼',atk:'3415',tier:1,skill:'战吼',skillNote:'暴龙咆哮范围伤害',rank:'一等',img:''},
    {name:'银须战炮',series:'银须',evo:'— → 银须之炮 → 银须战炮 → 银须战炮',atk:'3415',tier:1,skill:'重炮',skillNote:'重型炮击',rank:'一等',img:''},
    {name:'帝君圣箭',series:'帝君',evo:'— → 帝君之箭 → 帝君战箭 → 帝君圣箭',atk:'3415',tier:1,skill:'圣箭',skillNote:'帝君系列神圣之箭',rank:'一等',img:''},
    {name:'狮心幻刃',series:'狮心',evo:'— → 狮心之刃 → 狮心幻刃 → 狮心幻刃',atk:'3303',tier:1,skill:'幻刃',skillNote:'幻影利刃攻击',rank:'一等',img:''},
    {name:'凯旋重箭',series:'凯旋',evo:'— → 凯旋之箭 → 凯旋战箭 → 凯旋重箭',atk:'3415',tier:1,skill:'重箭',skillNote:'重型箭矢高额伤害',rank:'一等',img:''},
    {name:'兽王狂镖',series:'兽王',evo:'— → 兽王之镖 → 兽王战镖 → 兽王狂镖',atk:'3303',tier:1,skill:'狂镖',skillNote:'狂暴飞镖连射',rank:'一等',img:''},
    {name:'百媚幻花',series:'百媚',evo:'— → 百媚之花 → 百媚幻花 → 百媚幻花',atk:'3191',tier:2,skill:'幻花',skillNote:'魅惑花瓣散射',rank:'二等',img:''},
    {name:'烈阳神轮',series:'烈阳',evo:'— → 烈阳之轮 → 烈阳战轮 → 烈阳神轮',atk:'3415',tier:1,skill:'神轮',skillNote:'烈阳灼烧轮刃',rank:'一等',img:''},
    {name:'震海神翼',series:'震海',evo:'— → 震海之翼 → 震海战翼 → 震海神翼',atk:'3303',tier:1,skill:'神翼',skillNote:'波浪羽翼攻击',rank:'一等',img:''},
    {name:'永夜巨涡',series:'永夜',evo:'— → 永夜之涡 → 永夜巨涡 → 永夜巨涡',atk:'3415',tier:1,skill:'巨涡',skillNote:'暗夜漩涡吞噬敌人',rank:'一等',img:''},
    {name:'荆棘影蝶',series:'荆棘',evo:'— → 荆棘之蝶 → 荆棘战蝶 → 荆棘影蝶',atk:'3191',tier:2,skill:'影蝶',skillNote:'暗影蝴蝶追踪攻击',rank:'二等',img:''},
    {name:'苍穹神盾',series:'苍穹',evo:'— → 苍穹之盾 → 苍穹神盾 → 苍穹神盾',atk:'3303',tier:1,skill:'神盾',skillNote:'攻防一体神盾',rank:'一等',img:''},
    {name:'神火裂弹',series:'神火',evo:'— → 神火之弹 → 神火战弹 → 神火裂弹',atk:'3415',tier:1,skill:'裂弹',skillNote:'神火分裂弹幕',rank:'一等',img:''}
  ],
  wingman: [
    {name:'散弹机关炮',series:'机枪',evo:'机关炮 → 连发机关炮 → 散弹机关炮 → 散弹机关炮',atk:'2900',tier:5,skill:'机枪',skillNote:'普通散射弹幕',rank:'五等',img:''},
    {name:'米加巨炮',series:'米加',evo:'米加炮 → 米加粒子炮 → 米加巨炮 → 米加巨炮',atk:'3010',tier:4,skill:'激光',skillNote:'粒子激光穿透',rank:'四等',img:''},
    {name:'超高速火炮',series:'火炮',evo:'高速机枪 → 高速火炮 → 超高速火炮 → 超高速火炮',atk:'3150',tier:3,skill:'高速',skillNote:'超高速直线射击',rank:'三等',img:''},
    {name:'毁灭守卫',series:'守卫',evo:'守卫 → 钢铁守卫 → 金光守卫 → 毁灭守卫',atk:'3303',tier:2,skill:'防御',skillNote:'拦截敌方子弹，手残福音',rank:'二等',img:''},
    {name:'聚能电浆炮',series:'电浆',evo:'电浆炮 → 聚能电浆炮 → 聚能电浆炮 → 聚能电浆炮',atk:'3415',tier:1,skill:'贯穿',skillNote:'顶级贯穿电浆束',rank:'一等',img:''},
    {name:'超导电磁炮',series:'电磁',evo:'电磁炮 → 超导电磁炮 → 超导电磁炮 → 超导电磁炮',atk:'3415',tier:1,skill:'贯穿',skillNote:'电磁贯穿伤害',rank:'一等',img:''},
    {name:'饱和溶胶炮',series:'溶胶',evo:'溶胶炮 → 饱和溶胶炮 → 饱和溶胶炮 → 饱和溶胶炮',atk:'3303',tier:1,skill:'溶胶',skillNote:'粘着性持续伤害',rank:'一等',img:''},
    {name:'聚变液晶炮',series:'液晶',evo:'液晶炮 → 聚变液晶炮 → 聚变液晶炮 → 聚变液晶炮',atk:'3303',tier:1,skill:'聚变',skillNote:'液晶聚变高额伤害',rank:'一等',img:''},
    {name:'回光幻翼',series:'幻翼',evo:'幻翼 → 回光幻翼 → 回光幻翼 → 回光幻翼',atk:'3191',tier:2,skill:'回光',skillNote:'反射弹幕',rank:'二等',img:''},
    {name:'琴弦捕手',series:'琴弦',evo:'捕手 → 琴弦捕手 → 琴弦捕手 → 琴弦捕手',atk:'3303',tier:1,skill:'捕获',skillNote:'捕获敌方弹幕',rank:'一等',img:''},
    {name:'循环能量刃',series:'能量刃',evo:'能量刃 → 循环能量刃 → 循环能量刃 → 循环能量刃',atk:'3415',tier:1,skill:'循环',skillNote:'回旋能量刃攻击',rank:'一等',img:''},
    {name:'百变猎手',series:'猎手',evo:'猎手 → 百变猎手 → 百变猎手 → 百变猎手',atk:'3303',tier:1,skill:'变形',skillNote:'可变换多种攻击模式',rank:'一等',img:''},
    {name:'荧惑飞炎',series:'荧惑',evo:'飞炎 → 荧惑飞炎 → 荧惑飞炎 → 荧惑飞炎',atk:'3303',tier:1,skill:'飞炎',skillNote:'追踪火焰弹',rank:'一等',img:''},
    {name:'光棱护卫',series:'光棱',evo:'护卫 → 光棱护卫 → 光棱护卫 → 光棱护卫',atk:'3191',tier:2,skill:'光棱',skillNote:'光棱防御+反击',rank:'二等',img:''},
    {name:'极昼灯芯',series:'灯芯',evo:'灯芯 → 极昼灯芯 → 极昼灯芯 → 极昼灯芯',atk:'3303',tier:1,skill:'极昼',skillNote:'持续光照灼烧',rank:'一等',img:''},
    {name:'航迹光束',series:'航迹',evo:'光束 → 航迹光束 → 航迹光束 → 航迹光束',atk:'3303',tier:1,skill:'航迹',skillNote:'跟踪光束攻击',rank:'一等',img:''},
    {name:'数据化涡流',series:'涡流',evo:'涡流 → 数据化涡流 → 数据化涡流 → 数据化涡流',atk:'3415',tier:1,skill:'涡流',skillNote:'漩涡牵引持续伤害',rank:'一等',img:''},
    {name:'日冕光晕',series:'日冕',evo:'光晕 → 日冕光晕 → 日冕光晕 → 日冕光晕',atk:'3415',tier:1,skill:'日冕',skillNote:'日冕光环范围灼烧',rank:'一等',img:''},
    {name:'雅典战光',series:'雅典',evo:'— → 雅典之光 → 雅典战光 → 雅典战光',atk:'3415',tier:1,skill:'圣光',skillNote:'雅典系列神圣光芒',rank:'一等',img:''},
    {name:'暴龙战翼',series:'暴龙',evo:'— → 暴龙之翼 → 暴龙战翼 → 暴龙战翼',atk:'3415',tier:1,skill:'龙翼',skillNote:'暴龙翼击狂风',rank:'一等',img:''},
    {name:'银须战铳',series:'银须',evo:'— → 银须之铳 → 银须战铳 → 银须战铳',atk:'3415',tier:1,skill:'战铳',skillNote:'重型火铳轰击',rank:'一等',img:''},
    {name:'帝君圣威',series:'帝君',evo:'— → 帝君之威 → 帝君战威 → 帝君圣威',atk:'3415',tier:1,skill:'圣威',skillNote:'帝君系列神圣威压',rank:'一等',img:''},
    {name:'狮心幻焰',series:'狮心',evo:'— → 狮心之焰 → 狮心战焰 → 狮心幻焰',atk:'3303',tier:1,skill:'幻焰',skillNote:'幻影火焰攻击',rank:'一等',img:''},
    {name:'凯旋重刀',series:'凯旋',evo:'— → 凯旋之刀 → 凯旋战刀 → 凯旋重刀',atk:'3415',tier:1,skill:'重刀',skillNote:'重型刀锋切割',rank:'一等',img:''},
    {name:'兽王狂刀',series:'兽王',evo:'— → 兽王之刀 → 兽王战刀 → 兽王狂刀',atk:'3303',tier:1,skill:'狂刀',skillNote:'狂暴刀锋连斩',rank:'一等',img:''},
    {name:'百媚幻樱',series:'百媚',evo:'— → 百媚之樱 → 百媚战樱 → 百媚幻樱',atk:'3191',tier:2,skill:'幻樱',skillNote:'樱花幻影散射',rank:'二等',img:''},
    {name:'烈阳神乌',series:'烈阳',evo:'— → 烈阳之乌 → 烈阳战乌 → 烈阳神乌',atk:'3415',tier:1,skill:'神乌',skillNote:'金乌烈阳灼烧',rank:'一等',img:''},
    {name:'震海圣泉',series:'震海',evo:'— → 震海之泉 → 震海战泉 → 震海圣泉',atk:'3303',tier:1,skill:'圣泉',skillNote:'治愈泉水回复',rank:'一等',img:''},
    {name:'永夜幻刃',series:'永夜',evo:'— → 永夜之刃 → 永夜战刃 → 永夜幻刃',atk:'3415',tier:1,skill:'幻刃',skillNote:'暗夜幻影之刃',rank:'一等',img:''},
    {name:'荆棘耀枪',series:'荆棘',evo:'— → 荆棘之枪 → 荆棘战枪 → 荆棘耀枪',atk:'3191',tier:2,skill:'耀枪',skillNote:'荆棘光枪穿刺',rank:'二等',img:''},
    {name:'苍穹巨斧',series:'苍穹',evo:'— → 苍穹之斧 → 苍穹战斧 → 苍穹巨斧',atk:'3415',tier:1,skill:'巨斧',skillNote:'巨斧劈砍重击',rank:'一等',img:''},
    {name:'神火魔炎',series:'神火',evo:'— → 神火之炎 → 神火战炎 → 神火魔炎',atk:'3415',tier:1,skill:'魔炎',skillNote:'神火与魔焰双属性',rank:'一等',img:''}
  ]
};

window.GOD_DATA = {
  fighter: [
    {name:'强袭斗士',mats:'怒火凤凰 + 极光幻影',skill:'范围+激光',note:'入门级战神，零氪玩家首选',tier:3,img:''},
    {name:'自由悍将',mats:'神魔异形 + 智慧曙光',skill:'贯穿+散射',note:'经典战神，综合能力均衡',tier:2,img:''},
    {name:'暗夜神锋',mats:'智慧曙光 + 魔王刀锋',skill:'穿刺+斩击',note:'综合能力最强的战神',tier:1,img:''},
    {name:'冰河领主',mats:'魔王刀锋 + X翼冰河',skill:'斩击+急冻',note:'单体BOSS杀手，清兵稍弱',tier:1,img:''},
    {name:'暴雪女帝',mats:'X翼冰河 + 智慧曙光',skill:'急冻+散射',note:'冰系散射型战神',tier:2,img:''},
    {name:'绯红英灵',mats:'极光幻影 + 魔王刀锋',skill:'激光+斩击',note:'切割型战神',tier:2,img:''},
    {name:'千飓武神',mats:'异星魅影 + 镜面虚幻',skill:'魅影+反射',note:'幻影系融合战神',tier:2,img:''},
    {name:'斗战神猿',mats:'金箍神铁 + 跃动辉光',skill:'重击+辉光',note:'神铁辉光系战神',tier:2,img:''},
    {name:'玉影紫霞',mats:'紫霞铃音 + 绯霞流火',skill:'音波+流火',note:'铃音流火双属性融合',tier:2,img:''},
    {name:'重装泰坦',mats:'彩翼分辉 + 合金幻刃',skill:'分光+合金',note:'重型装甲战神',tier:2,img:''},
    {name:'金源武圣',mats:'星火蜉蝣 + 星辉夜蝠',skill:'蜉蝣+暗袭',note:'蜉蝣夜蝠顶级融合',tier:1,img:''},
    {name:'雅典女神',mats:'雅典系列合成',skill:'神火',note:'雅典系列专属战神',tier:1,img:''},
    {name:'暴龙突击',mats:'暴龙系列合成',skill:'撕裂',note:'暴龙系列专属战神',tier:1,img:''},
    {name:'银须首领',mats:'银须系列合成',skill:'重锤',note:'银须系列专属战神',tier:1,img:''},
    {name:'帝君嬴皇',mats:'帝君系列合成',skill:'圣斩',note:'帝君系列专属战神',tier:1,img:''},
    {name:'狮心圣骑',mats:'狮心系列合成',skill:'冲锋',note:'狮心系列专属战神',tier:1,img:''},
    {name:'凯旋大帝',mats:'凯旋系列合成',skill:'重斩',note:'凯旋系列专属战神',tier:1,img:''},
    {name:'兽王忍侍',mats:'兽王系列合成',skill:'狂野',note:'兽王系列专属战神',tier:1,img:''},
    {name:'百魅妖狐',mats:'百媚系列合成',skill:'魅惑',note:'百媚系列专属战神',tier:2,img:''},
    {name:'烈阳主宰',mats:'烈阳系列合成',skill:'烈阳',note:'烈阳系列专属战神',tier:1,img:''},
    {name:'震海霸主',mats:'震海系列合成',skill:'波涛',note:'震海系列专属战神',tier:1,img:''},
    {name:'永夜魔君',mats:'永夜系列合成',skill:'永夜',note:'永夜系列专属战神',tier:1,img:''},
    {name:'银色荆棘',mats:'荆棘系列合成',skill:'穿刺',note:'荆棘系列专属战神',tier:2,img:''},
    {name:'苍穹战魂',mats:'苍穹系列合成',skill:'投射',note:'苍穹系列专属战神',tier:1,img:''},
    {name:'神火流焰',mats:'神火系列合成',skill:'神焰',note:'神火系列专属战神',tier:1,img:''}
  ],
  armor: [
    {name:'止战金魂',mats:'黄金之铠 + 聚能之光',skill:'战魂+荣耀',note:'擦分+受伤暴走，攻防一体',tier:2,img:''},
    {name:'守月魔殇',mats:'魔龙之鳞 + 月光之轮',skill:'龙血+守护',note:'自动回血+暴走护盾，生存顶级',tier:1,img:''},
    {name:'原力华轮',mats:'原生之华 + 月光之轮',skill:'转化+守护',note:'吃水晶回血+暴走护盾',tier:1,img:''},
    {name:'永世决意',mats:'金刚之盾 + 神圣之力',skill:'钢盾+神圣',note:'概率减伤+防秒杀，新手过渡',tier:3,img:''},
    {name:'净莲芳华',mats:'原生之华 + 红莲之怒',skill:'转化+反伤',note:'回血+火焰反伤双重效果',tier:1,img:''},
    {name:'怒血金甲',mats:'血怒之心进阶合成',skill:'血怒强化',note:'护盾期间攻击力+50%',tier:2,img:''}
  ],
  sub: [
    {name:'星光爆裂',mats:'聚能爆破弹 + 超导激光',skill:'爆破+锁定',note:'贯穿爆炸+自动锁定',tier:1,img:''},
    {name:'闪电核弹',mats:'闪电新星 + 融合核弹',skill:'追踪+范围',note:'追踪闪电+核弹大范围',tier:2,img:''},
    {name:'彻翼巡星',mats:'贫铀穿甲弹 + 巡航导弹',skill:'贯穿+跟踪',note:'穿透追踪兼备，新手过渡',tier:3,img:''},
    {name:'死光晶孢',mats:'超导激光 + 噬能孢子',skill:'锁定+吞噬',note:'暗夜神锋套装核心配件',tier:1,img:''},
    {name:'曲率振波',mats:'噬能孢子 + 震荡干涉波',skill:'吞噬+震荡',note:'冰河领主套装核心配件',tier:1,img:''},
    {name:'月光银铃',mats:'后期特殊合成',skill:'机枪+盘旋',note:'多段伤害覆盖',tier:2,img:''},
    {name:'斥力破片',mats:'后期特殊合成',skill:'扫射+贯穿',note:'破片扫射清场',tier:2,img:''}
  ],
  wing: [
    {name:'极速守卫',mats:'超高速火炮 + 毁灭守卫',skill:'环射+防御',note:'360°螺旋弹幕+挡子弹',tier:2,img:''},
    {name:'量子磁流炮',mats:'聚能电浆炮 + 超导电磁炮',skill:'穿甲+贯穿',note:'双贯穿属性叠加',tier:1,img:''},
    {name:'广域流星炮',mats:'超导电磁炮 + 饱和溶胶炮',skill:'贯穿+溶胶',note:'暗夜神锋套装核心配件',tier:1,img:''},
    {name:'末日熔岩炮',mats:'饱和溶胶炮 + 聚变液晶炮',skill:'溶胶+聚变',note:'冰河领主套装核心配件',tier:1,img:''},
    {name:'荧惑守心',mats:'荧惑飞炎进阶合成',skill:'追踪+散射',note:'追踪火焰散射',tier:2,img:''},
    {name:'狼爪光束',mats:'后期特殊合成',skill:'光束+撕裂',note:'后期高输出僚机',tier:2,img:''}
  ]
};
